# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-07 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repoM', '0001_initial'),
        ('login', '0002_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_sha', models.CharField(max_length=50)),
                ('release_time', models.DateField(auto_now_add=True)),
                ('env', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128, unique=True)),
                ('project_type', models.CharField(choices=[('Internal', '内部项目'), ('Outgoing', '外部项目')], default='Internal', max_length=20)),
                ('description', models.TextField()),
                ('c_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateField(auto_now_add=True)),
                ('release_version', models.CharField(max_length=20)),
                ('release_note', models.TextField()),
                ('ProjectList', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectM.ProjectList')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(default='branch-dev', max_length=20)),
                ('build_url', models.URLField(null=True)),
                ('CodeRepo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repoM.CodeRepo')),
                ('ProjectList', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectM.ProjectList')),
                ('deploy_host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repoM.DeployHost')),
            ],
        ),
        migrations.AddField(
            model_name='projectlist',
            name='code_repo',
            field=models.ManyToManyField(through='projectM.ProjectRepo', to='repoM.CodeRepo'),
        ),
        migrations.AddField(
            model_name='coderelease',
            name='Project_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectM.ProjectRelease'),
        ),
        migrations.AddField(
            model_name='coderelease',
            name='code_repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repoM.CodeRepo'),
        ),
    ]
