# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-02 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectM', '0002_auto_20190401_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='project_key',
            field=models.CharField(default='JST', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
