# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-26 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('fullname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=20)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
            },
        ),
    ]
