# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-01 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='chuanxiao.li@jieshunpay.cn', max_length=120),
        ),
    ]
