# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-07 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=128)),
                ('repo_group', models.CharField(max_length=123)),
                ('repo_url', models.URLField()),
                ('rpeo_description', models.TextField()),
            ],
            options={
                'ordering': ['-repo_group'],
            },
        ),
        migrations.CreateModel(
            name='DeployHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField()),
                ('host_username', models.CharField(max_length=30)),
                ('host_password', models.CharField(max_length=30)),
                ('host_port', models.IntegerField(default=22)),
                ('host_description', models.TextField()),
                ('c_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_url', models.URLField()),
                ('sys_username', models.CharField(max_length=128)),
                ('sys_password', models.CharField(max_length=128)),
                ('sys_type', models.CharField(max_length=20)),
                ('c_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-c_time'],
            },
        ),
    ]
