# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-12 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repoM', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemConfig',
        ),
    ]
