# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-12 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoM', '0002_delete_systemconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_url', models.URLField()),
                ('sys_username', models.CharField(max_length=128)),
                ('sys_password', models.CharField(max_length=128)),
                ('sys_version', models.CharField(max_length=20)),
                ('sys_description', models.CharField(max_length=100)),
                ('sys_type', models.CharField(max_length=20)),
                ('c_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-c_time'],
            },
        ),
    ]
