# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-18 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repoM', '0004_auto_20190318_1106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemConfig',
        ),
    ]
