# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-18 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoM', '0005_delete_systemconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_name', models.CharField(max_length=20, unique=True)),
                ('sys_url', models.URLField()),
                ('sys_api_url', models.URLField(blank=True, null=True)),
                ('sys_username', models.CharField(max_length=128)),
                ('sys_password', models.CharField(max_length=128)),
                ('sys_privatetoken', models.CharField(blank=True, max_length=50, null=True)),
                ('sys_version', models.CharField(max_length=20)),
                ('sys_description', models.TextField(max_length=200)),
                ('sys_type', models.CharField(choices=[('git', 'Git 源码管理系统'), ('svn', 'SVN 源码管理系统'), ('jenkins', 'Jenkins 构建服务'), ('nexus', 'Nexus 依赖管理系统'), ('others', '其他项目管理系统')], max_length=20)),
                ('sys_lable', models.CharField(blank=True, max_length=20, null=True)),
                ('c_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-c_time'],
            },
        ),
    ]
