# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-26 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoM', '0006_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='coderepo',
            name='repo_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coderepo',
            name='repo_system',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
